language: php

php:
  - 7.0
  - 7.1

sudo: true

cache: vendor

services:
  - redis-server

before_script:
  - echo 'extension=redis.so' >> $HOME/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer global require hirak/prestissimo --no-interaction --quiet
  - composer install --no-interaction --quiet

script:
  - composer test
  - composer csfixer

after_success:
  - mkdir -p /tmp/build/coverage
  - composer quality
  - composer coverage

notifications:
  email: false

# vim:fdl=0:sts=2:sw=2:ts=2
